{
  "swagger": "2.0",
  "info": {
    "title": "ERP",
    "description": "Documentation from API",
    "version": "1.0.0"
  },
  "basePath": "/",
  "paths": {
    "/api/user/login": {
      "post": {
        "tags": [
          "User"
        ],
        "description": "Autenticação de usuário e obtenção do token",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "description": "E-mail do usuário"
                  },
                  "password": {
                    "type": "string",
                    "description": "Senha do usuário"
                  }
                },
                "example": {
                  "email": "usuario@example.com",
                  "password": "senha123"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Sucesso na autenticação, retorna o token e informações do usuário",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string",
                      "description": "Token de autenticação"
                    },
                    "message": {
                      "type": "string",
                      "description": "Mensagem de sucesso"
                    },
                    "user": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string",
                          "description": "Nome do usuário"
                        },
                        "email": {
                          "type": "string",
                          "description": "E-mail do usuário"
                        },
                        "photo": {
                          "type": "string",
                          "description": "URL da foto do usuário"
                        },
                        "privileges": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          },
                          "description": "Lista de privilégios do usuário"
                        }
                      }
                    }
                  },
                  "example": {
                    "token": "token_de_autenticacao_aqui",
                    "message": "Olá usuário",
                    "user": {
                      "name": "Nome do Usuário",
                      "email": "usuario@example.com",
                      "photo": "url_da_foto",
                      "privileges": [
                        "admin",
                        "editor"
                      ]
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Requisição inválida ou erro na autenticação",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "Mensagem de erro"
                    }
                  },
                  "example": {
                    "message": "E-mail ou senha inválidos"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/user/{userId}/profile": {
      "get": {
        "tags": [
          "User"
        ],
        "description": "Obter perfil de um usuário pelo ID",
        "parameters": [
          {
            "in": "path",
            "name": "userId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Sucesso na obtenção do perfil do usuário",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string",
                      "description": "Nome do usuário"
                    },
                    "photo": {
                      "type": "string",
                      "description": "URL da foto do usuário"
                    },
                    "email": {
                      "type": "string",
                      "description": "E-mail do usuário"
                    },
                    "id": {
                      "type": "string",
                      "description": "ID do usuário"
                    }
                  },
                  "example": {
                    "name": "Nome do Usuário",
                    "photo": "url_da_foto",
                    "email": "usuario@example.com",
                    "id": "id_do_usuario"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Requisição inválida ou erro na obtenção do perfil do usuário",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "Mensagem de erro"
                    }
                  },
                  "example": {
                    "message": "Usuário não encontrado"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/user/{userId}/password": {
      "patch": {
        "tags": [
          "User"
        ],
        "description": "Atualizar senha de um usuário pelo ID",
        "parameters": [
          {
            "in": "path",
            "name": "userId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "password": {
                    "type": "string",
                    "description": "Nova senha do usuário"
                  }
                },
                "example": {
                  "password": "nova_senha123"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Sucesso na atualização da senha do usuário",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "Mensagem de sucesso"
                    }
                  },
                  "example": {
                    "message": "Senha do usuário atualizada com sucesso!"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Requisição inválida ou erro na atualização da senha do usuário",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "Mensagem de erro"
                    }
                  },
                  "example": {
                    "message": "A nova senha não foi fornecida"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/forgot/generate-code": {
      "post": {
        "tags": [
          "Recuperação de Senha"
        ],
        "summary": "Gera e envia o código de recuperação de senha",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string",
                  "format": "email"
                }
              },
              "required": [
                "email"
              ]
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Código de recuperação enviado com sucesso",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "Erro ao gerar ou enviar o código de recuperação",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          },
          "404": {
            "description": "E-mail não encontrado na tabela de usuários",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/api/forgot/verify-code": {
      "post": {
        "tags": [
          "Recuperação de Senha"
        ],
        "summary": "Verifica o código de recuperação de senha",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string",
                  "format": "email"
                },
                "code": {
                  "type": "string"
                }
              },
              "required": [
                "email",
                "code"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Código de recuperação válido",
            "schema": {
              "type": "object",
              "properties": {
                "userId": {
                  "type": "string"
                },
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "Erro ao verificar o código de recuperação",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          },
          "404": {
            "description": "Código inválido para o e-mail fornecido",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/api/user": {
      "get": {
        "tags": [
          "User"
        ],
        "description": "Buscar usuários por nome ou ID",
        "parameters": [
          {
            "in": "query",
            "name": "name",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "id",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "page",
            "required": false,
            "schema": {
              "type": "integer",
              "default": 1
            }
          },
          {
            "in": "query",
            "name": "pageSize",
            "required": false,
            "schema": {
              "type": "integer",
              "default": 10
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Sucesso na busca de usuários",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "user": {
                        "type": "object",
                        "properties": {
                          "name": {
                            "type": "string",
                            "description": "Nome do usuário"
                          },
                          "email": {
                            "type": "string",
                            "description": "E-mail do usuário"
                          },
                          "photo": {
                            "type": "string",
                            "description": "URL da foto do usuário"
                          }
                        }
                      }
                    }
                  }
                },
                "example": [
                  {
                    "user": {
                      "name": "Nome do Usuário 1",
                      "email": "usuario1@example.com",
                      "photo": "url_da_foto1"
                    }
                  },
                  {
                    "user": {
                      "name": "Nome do Usuário 2",
                      "email": "usuario2@example.com",
                      "photo": "url_da_foto2"
                    }
                  }
                ]
              }
            }
          },
          "400": {
            "description": "Requisição inválida ou erro na busca de usuários",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "Mensagem de erro"
                    }
                  },
                  "example": {
                    "message": "Usuário não encontrado"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "User"
        ],
        "description": "Cadastrar um novo usuário",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "example": {
                "email": "novo_usuario@example.com",
                "password": "senha123",
                "name": "Novo Usuário",
                "photo": "url_da_foto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Sucesso no cadastro do usuário",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "Mensagem de sucesso"
                    }
                  },
                  "example": {
                    "message": "Usuário cadastrado com sucesso!"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Requisição inválida ou erro no cadastro do usuário",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "Mensagem de erro"
                    }
                  },
                  "example": {
                    "message": "Erro ao cadastrar usuário"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/user/{userId}": {
      "get": {
        "tags": [
          "User"
        ],
        "description": "Obter informações de um usuário pelo ID",
        "parameters": [
          {
            "in": "path",
            "name": "userId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Sucesso na obtenção das informações do usuário",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string",
                      "description": "Nome do usuário"
                    },
                    "email": {
                      "type": "string",
                      "description": "E-mail do usuário"
                    },
                    "photo": {
                      "type": "string",
                      "description": "URL da foto do usuário"
                    }
                  },
                  "example": {
                    "name": "Nome do Usuário",
                    "email": "usuario@example.com",
                    "photo": "url_da_foto"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Requisição inválida ou erro na obtenção das informações do usuário",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "Mensagem de erro"
                    }
                  },
                  "example": {
                    "message": "Usuário não encontrado"
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "User"
        ],
        "description": "Atualizar informações de um usuário pelo ID",
        "parameters": [
          {
            "in": "path",
            "name": "userId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "example": {
                "email": "usuario_atualizado@example.com",
                "name": "Usuário Atualizado",
                "photo": "nova_url_da_foto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Sucesso na atualização das informações do usuário",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "Mensagem de sucesso"
                    }
                  },
                  "example": {
                    "message": "Usuário atualizado com sucesso!"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Requisição inválida ou erro na atualização das informações do usuário",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "Mensagem de erro"
                    }
                  },
                  "example": {
                    "message": "Erro ao atualizar usuário"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "User"
        ],
        "description": "Excluir um usuário pelo ID",
        "parameters": [
          {
            "in": "path",
            "name": "userId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Sucesso na exclusão do usuário",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "Mensagem de sucesso"
                    }
                  },
                  "example": {
                    "message": "Usuário excluído com sucesso!"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Requisição inválida ou erro na exclusão do usuário",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "Mensagem de erro"
                    }
                  },
                  "example": {
                    "message": "Erro ao excluir usuário"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/user/{userId}/privilege": {
      "get": {
        "tags": [
          "User"
        ],
        "description": "Obter privilégios de um usuário pelo ID",
        "parameters": [
          {
            "in": "path",
            "name": "userId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Sucesso na obtenção dos privilégios do usuário",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "privileges": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      },
                      "description": "Lista de privilégios do usuário"
                    }
                  },
                  "example": {
                    "privileges": [
                      "admin",
                      "editor"
                    ]
                  }
                }
              }
            }
          },
          "404": {
            "description": "Usuário não encontrado ou erro na obtenção dos privilégios do usuário",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "Mensagem de erro"
                    }
                  },
                  "example": {
                    "message": "Privilégios do usuário não encontrados"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/user/{userId}/permission-key": {
      "get": {
        "tags": [
          "User"
        ],
        "description": "Obter chave de permissão de um usuário pelo ID e nome da permissão",
        "parameters": [
          {
            "in": "path",
            "name": "userId",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "permissionName",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Sucesso na obtenção da chave de permissão do usuário",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "key": {
                      "type": "string",
                      "description": "Chave de permissão do usuário"
                    }
                  },
                  "example": {
                    "key": "chave_de_permissao_aqui"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Usuário não encontrado ou erro na obtenção da chave de permissão do usuário",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "Mensagem de erro"
                    }
                  },
                  "example": {
                    "message": "Permissão não encontrada para o usuário"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/notifications": {
      "post": {
        "tags": [
          "Notificações"
        ],
        "summary": "Cria e envia uma notificação",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "receivedBy": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "message": {
                  "type": "string"
                },
                "title": {
                  "type": "string"
                },
                "sentBy": {
                  "type": "string"
                },
                "isGlobal": {
                  "type": "boolean"
                }
              },
              "required": [
                "message",
                "title",
                "sentBy"
              ]
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Notificação enviada com sucesso",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "Erro ao enviar notificação",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/api/notifications/{userId}": {
      "get": {
        "tags": [
          "Notificações"
        ],
        "summary": "Obtém as notificações de um usuário",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "page",
            "in": "query",
            "required": false,
            "type": "integer"
          },
          {
            "name": "perPage",
            "in": "query",
            "required": false,
            "type": "integer"
          }
        ],
        "responses": {
          "200": {
            "description": "Notificações obtidas com sucesso",
            "schema": {
              "type": "object",
              "properties": {
                "directNotifications": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/Notification"
                  }
                },
                "globalNotifications": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/Notification"
                  }
                },
                "directNotificationsCount": {
                  "type": "integer"
                },
                "globalNotificationsCount": {
                  "type": "integer"
                }
              }
            }
          },
          "400": {
            "description": "Erro ao obter notificações",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/api/notifications/sent/{userId}": {
      "get": {
        "tags": [
          "Notificações"
        ],
        "summary": "Obtém as notificações enviadas por um usuário",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "page",
            "in": "query",
            "required": false,
            "type": "integer"
          },
          {
            "name": "perPage",
            "in": "query",
            "required": false,
            "type": "integer"
          }
        ],
        "responses": {
          "200": {
            "description": "Notificações enviadas obtidas com sucesso",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Notification"
              }
            }
          },
          "400": {
            "description": "Erro ao obter notificações enviadas",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/api/notifications/{notificationId}": {
      "delete": {
        "tags": [
          "Notificações"
        ],
        "summary": "Exclui uma notificação",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "notificationId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "userId",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Notificação excluída com sucesso",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "Erro ao excluir notificação",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/api/notifications/{notificationId}/mark-as-read": {
      "put": {
        "tags": [
          "Notificações"
        ],
        "summary": "Marca uma notificação como lida",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "notificationId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "userId",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Notificação marcada como lida com sucesso",
            "schema": {
              "$ref": "#/definitions/Notification"
            }
          },
          "400": {
            "description": "Erro ao marcar notificação como lida",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/api/notifications/unread-count/{userId}": {
      "get": {
        "tags": [
          "Notificações"
        ],
        "summary": "Obtém a contagem de notificações não lidas de um usuário",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Contagem de notificações não lidas obtida com sucesso",
            "schema": {
              "type": "object",
              "properties": {
                "count": {
                  "type": "integer"
                }
              }
            }
          },
          "400": {
            "description": "Erro ao obter contagem de notificações não lidas",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/api/permission": {
      "post": {
        "tags": [
          "Permissões"
        ],
        "summary": "Cria uma nova permissão",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "createdAt": {
                  "type": "string",
                  "format": "date-time"
                },
                "createdByUser": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                },
                "key": {
                  "type": "string"
                }
              },
              "required": [
                "name",
                "createdAt",
                "createdByUser",
                "description",
                "key"
              ]
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Permissão criada com sucesso",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "default": true
                },
                "message": {
                  "type": "string"
                },
                "data": {
                  "$ref": "#/definitions/Permission"
                }
              }
            }
          },
          "400": {
            "description": "Erro ao criar permissão",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "default": false
                },
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "Permissões"
        ],
        "summary": "Lista todas as permissões",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Permissões listadas com sucesso",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Permission"
              }
            }
          },
          "400": {
            "description": "Erro ao listar permissões",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "default": false
                },
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/api/permissions/{PermissionId}": {
      "delete": {
        "tags": [
          "Permissões"
        ],
        "summary": "Exclui uma permissão por ID",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "PermissionId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Permissão excluída com sucesso",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "Erro ao excluir permissão",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "default": false
                },
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/api/permissions/search": {
      "get": {
        "tags": [
          "Permissões"
        ],
        "summary": "Pesquisa permissões com base em um termo de busca",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "searchTerm",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "page",
            "in": "query",
            "required": false,
            "type": "integer"
          },
          {
            "name": "perPage",
            "in": "query",
            "required": false,
            "type": "integer"
          }
        ],
        "responses": {
          "200": {
            "description": "Permissões pesquisadas com sucesso",
            "schema": {
              "type": "object",
              "properties": {
                "page": {
                  "type": "integer"
                },
                "perPage": {
                  "type": "integer"
                },
                "totalPages": {
                  "type": "integer"
                },
                "totalItems": {
                  "type": "integer"
                },
                "permissions": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/Permission"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Erro ao pesquisar permissões",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "default": false
                },
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/api/permissions/search-by-name": {
      "get": {
        "tags": [
          "Permissões"
        ],
        "summary": "Pesquisa uma permissão pelo nome",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "name",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Permissão encontrada com sucesso",
            "schema": {
              "$ref": "#/definitions/Permission"
            }
          },
          "400": {
            "description": "Erro ao pesquisar permissão pelo nome",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "default": false
                },
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "404": {
            "description": "Permissão não encontrada",
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean",
                  "default": false
                },
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Notification": {
      "type": "object",
      "properties": {
        "receivedBy": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "message": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "sentBy": {
          "type": "string"
        },
        "timestamp": {
          "type": "string",
          "format": "date-time"
        },
        "createdAt": {
          "type": "string",
          "format": "date-time"
        },
        "isRead": {
          "type": "boolean"
        },
        "isGlobal": {
          "type": "boolean"
        },
        "excludedFor": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "readBy": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "paths": {
      "/api/privileges": {
        "post": {
          "tags": [
            "Privilégios"
          ],
          "summary": "Cria um novo privilégio",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "body",
              "in": "body",
              "required": true,
              "schema": {
                "$ref": "#/definitions/Privilege"
              }
            }
          ],
          "responses": {
            "201": {
              "description": "Privilégio criado com sucesso",
              "schema": {
                "$ref": "#/definitions/PrivilegeResponse"
              }
            },
            "400": {
              "description": "Erro ao criar privilégio",
              "schema": {
                "$ref": "#/definitions/ErrorResponse"
              }
            }
          }
        },
        "get": {
          "tags": [
            "Privilégios"
          ],
          "summary": "Lista todos os privilégios",
          "produces": [
            "application/json"
          ],
          "responses": {
            "200": {
              "description": "Privilégios listados com sucesso",
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/definitions/Privilege"
                }
              }
            },
            "400": {
              "description": "Erro ao listar privilégios",
              "schema": {
                "$ref": "#/definitions/ErrorResponse"
              }
            }
          }
        }
      },
      "/api/privileges/{PrivilegeId}": {
        "put": {
          "tags": [
            "Privilégios"
          ],
          "summary": "Atualiza um privilégio pelo ID",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "PrivilegeId",
              "in": "path",
              "required": true,
              "type": "string"
            },
            {
              "name": "body",
              "in": "body",
              "required": true,
              "schema": {
                "$ref": "#/definitions/Privilege"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Privilégio atualizado com sucesso",
              "schema": {
                "$ref": "#/definitions/Privilege"
              }
            },
            "400": {
              "description": "Erro ao atualizar privilégio",
              "schema": {
                "$ref": "#/definitions/ErrorResponse"
              }
            }
          }
        },
        "delete": {
          "tags": [
            "Privilégios"
          ],
          "summary": "Exclui um privilégio pelo ID",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "PrivilegeId",
              "in": "path",
              "required": true,
              "type": "string"
            }
          ],
          "responses": {
            "204": {
              "description": "Privilégio excluído com sucesso"
            },
            "400": {
              "description": "Erro ao excluir privilégio",
              "schema": {
                "$ref": "#/definitions/ErrorResponse"
              }
            }
          }
        },
        "get": {
          "tags": [
            "Privilégios"
          ],
          "summary": "Obtém um privilégio pelo ID",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "PrivilegeId",
              "in": "path",
              "required": true,
              "type": "string"
            }
          ],
          "responses": {
            "200": {
              "description": "Privilégio obtido com sucesso",
              "schema": {
                "$ref": "#/definitions/Privilege"
              }
            },
            "400": {
              "description": "Erro ao obter privilégio",
              "schema": {
                "$ref": "#/definitions/ErrorResponse"
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "description": "E-mail do usuário"
          },
          "password": {
            "type": "string",
            "description": "Senha do usuário"
          },
          "name": {
            "type": "string",
            "description": "Nome do usuário"
          },
          "photo": {
            "type": "string",
            "description": "URL da foto do usuário"
          }
        },
        "example": {
          "email": "usuario@example.com",
          "password": "senha123",
          "name": "Nome do Usuário",
          "photo": "url_da_foto"
        }
      }
    }
  }
}